apiVersion: v1
kind: Service
metadata:
   name: db #pod'lar birbirleriyle konusurken bu name ile iletisim kurarlar
   labels: 
      name: postgres-service
      app: demo-voting-app
spec:
   ports:
     - port: 5432
       targetPort: 5432
   selector: # pod'daki labellar
      name: postgres-pod
      app: demo-voting-app