apiVersion: v1
kind: Service
metadata:
   name: redis #pod'lar birbirleriyle konusurken bu name ile iletisim kurarlar
   labels: 
      name: redis-service
      app: demo-voting-app
spec:
   ports:
     - port: 6379 
       targetPort: 6379
   selector: # pod'daki labellar
      name: redis-pod
      app: demo-voting-app