apiVersion: v1
kind: Service
metadata:
   name: voting-service #pod'lar birbirleriyle konusurken bu name ile iletisim kurarlar
   labels: 
      name: voting-service
      app: demo-voting-app
spec:
   type: NodePort #disarisi ile iletisime gececegi icin disariya acmamiza yarar
   ports:
     - port: 80
       targetPort: 80
       nodePort: 30004
   selector: # pod'daki labellar
      name: voting-app-pod
      app: demo-voting-app